// DO NOT EDIT!
// Code generated by ffjson <https://github.com/pquerna/ffjson>
// source: ./session.go
// DO NOT EDIT!
// Ups ... it's edited ...
package picnic

import (
	"bytes"

	"github.com/SchumacherFM/wanderlust/helpers"
)

func (mj *SessionInfo) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	buf.Grow(1024)
	err := mj.MarshalJSONBuf(&buf)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
func (mj *SessionInfo) MarshalJSONBuf(buf *bytes.Buffer) error {
	var err error
	var obj []byte
	var first bool = true
	_ = obj
	_ = err
	_ = first
	buf.WriteString(`{`)
	if first == true {
		first = false
	} else {
		buf.WriteString(`,`)
	}
	buf.WriteString(`"email":`)
	helpers.Ffjson_WriteJsonString(buf, mj.Email)
	if first == true {
		first = false
	} else {
		buf.WriteString(`,`)
	}
	buf.WriteString(`"isAdmin":`)
	if mj.IsAdmin {
		buf.WriteString(`true`)
	} else {
		buf.WriteString(`false`)
	}
	if first == true {
		first = false
	} else {
		buf.WriteString(`,`)
	}
	buf.WriteString(`"loggedIn":`)
	if mj.LoggedIn {
		buf.WriteString(`true`)
	} else {
		buf.WriteString(`false`)
	}
	if first == true {
		first = false
	} else {
		buf.WriteString(`,`)
	}
	buf.WriteString(`"name":`)
	helpers.Ffjson_WriteJsonString(buf, mj.Name)
	if first == true {
		first = false
	} else {
		buf.WriteString(`,`)
	}
	buf.WriteString(`"userName":`)
	helpers.Ffjson_WriteJsonString(buf, mj.UserName)
	buf.WriteString(`}`)
	return nil
}
